# Generated by Django 3.2.13 on 2022-04-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drscm', '0002_fixedtravel_hourlytravel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlytravel',
            name='hours',
            field=models.FloatField(),
        ),
    ]
