# Generated by Django 3.2.13 on 2022-04-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drscm', '0002_fixedtravel_hourlytravel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='owner',
        ),
    ]
