# Generated by Django 3.2.13 on 2022-04-26 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drscm', '0003_alter_hourlytravel_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedtravel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hourlytravel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
