# Generated by Django 3.2.13 on 2022-04-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drscm", "0004_change_travel_ids_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedtravel",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hourlytravel",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
