# Generated by Django 3.2.13 on 2022-04-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drscm', '0006_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksession',
            options={'ordering': ('start_timestamp',)},
        ),
    ]
