# Generated by Django 3.2.13 on 2022-04-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drscm", "0007_alter_worksession_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkSessionProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("drscm.worksession",),
        ),
    ]
