# Generated by Django 3.2.13 on 2022-04-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drscm", "0010_fixedtravelproxy_hourlytravelproxy_invoiceproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="hourly_rate",
            field=models.FloatField(default=175),
        ),
        migrations.AlterField(
            model_name="project",
            name="travel_fixed_rate",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="travel_hourly_rate",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
