# Generated by Django 3.2.13 on 2022-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drscm", "0012_auto_20220429_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="tax_regulation",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "DUTCH"), (1, "EUROPEAN"), (2, "NON_EUROPEAN")], default=0
            ),
        ),
    ]
