# Generated by Django 3.2.13 on 2022-05-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drscm', '0013_invoice_tax_regulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedtravel',
            name='extra_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hourlytravel',
            name='extra_costs',
            field=models.FloatField(default=0),
        ),
    ]
