name: Run django tests

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "UTC"
      - name: Run Tests
        working-directory: ./backend
        run: |
          python manage.py test